name: Docker Image CI

on:
  push:
    branches: [ "operator" ]

jobs:
  build-hub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        registry: "ghcr.io"
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        file: ./Dockerfile
        tags: ghcr.io/yiffyi/xfbbroker:latest
        platforms: linux/amd64,linux/arm64
        push: true
        cache-from: type=registry,ref=ghcr.io/yiffyi/xfbbroker:latest
        cache-to: type=inline